/*Programming Challenge: Gym Membership Fees Increase
Section 5, Lecture 18

A gym currently charges $29.99 per month.  It has stated that it raises its monthly fee at the start of every year by 2%.

Write a program which uses a for loop to display the expected rates year by year for a number of years from now between 3 and 10 years 
(this means you should generate a random integer between 3 and 10).  For example, if the randomly generated year was 4, then the program 
would log 4 statements to the console which each say the year followed by the expected monthly fee for that year.*/

// The starting year is 2019 since that is the current year
let year = 2019;

// The initial membership fee is $29.99
let memFee = 29.99;

// The variable time is assigned a random integer between 3 and 10
const time = Math.floor(Math.random() * 8) + 3;

// This for loop displays the expected monthly rates year by year. It starts at 0 and runs the number of
// times randomly generated by the variable time minus 1.
for (let i = 0; i < time; i++) {
    // Each time the for loop runs, 1 will be added to the year.
    year++;
    
    // Each year, the monthly membership fee will be 2% higher.
    memFee *= 1.02;
    
    // This prints the year and the expected monthly fee for that year each time the for loop runs its code.
    console.log("In " + year + ", the monthly gym membership fee will be $" + memFee.toFixed(2) + "."); 
}