/*Programming Challenge: Movie Theater Seating
Section 8, Lecture 36

For this programming challenge, you will create a program that simulates the seats in a movie theater using a 2D array and calculates total 
revenue based on the seating chart represented by that array.  You will start by creating 2 functions:

    The first function will create the 2D array and will take 2 randomly generated numbers as inputs.  In relation to the 2D array that the 
    function is creating, the first input represents the number of rows, and the second input represents the number of columns.  Inside the 
    function, the array should have all of its indexes filled in with random integers between and inclusive of the range 0 to 4.  
    After creating the array, the function should end by returning it.

    The second function should take the array created by the first function as its input.  Then, it should calculate and return the total 
    revenue (with 2 decimal numbers displayed after the decimal point) based on the numbers of the array representing the following types 
    of customers:

        0 represents an empty seat, which means no revenue.

        1 represents an adult.  The price of 1 ticket for an adult is $9.00.

        2 represents a child.  The price of 1 ticket for a child is $7.00.

        3 represents a senior citizen.  The price of 1 ticket for a senior citizen is $8.00.

        4 represents a student.  The price for 1 ticket after the student discount is applied is $8.50.

At the end of your program, you should call the first function with 2 randomly generated integers each between and inclusive of 
the range 5 to 15 as its inputs.  Log what is returned to the console. 

After that, call the second function with the array generated by the first function as its input.  Log what is returned to the console.*/

